In [16]:
import numpy as np
a = np.array( [np.arange(6)+ 10*i for i in np.arange(6)] )
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [17]:
a[ (0,1,2,3,4),(1,2,3,4,5) ]

array([ 1, 12, 23, 34, 45])

In [18]:
# subsetting the rows beginning with
a[3:, [0,2,5]]

array([[30, 32, 35],
       [40, 42, 45],
       [50, 52, 55]])

In [22]:
mask = np.array([1,0,1,0,0,1], dtype = bool)
a[mask,2]

array([ 2, 22, 52])

In [ ]:
# creating a new column


In [23]:
# Broadcasting in numpy
# only exception with - when we are operating with mismatching dimensions

mileposts = np.array([0, 198, 303, 736, 871, 1175, 1475,
1544,1913, 2448])
distance_array = np.abs(mileposts - mileposts[:, np.newaxis])
distance_array

array([[   0,  198,  303,  736,  871, 1175, 1475, 1544, 1913, 2448],
       [ 198,    0,  105,  538,  673,  977, 1277, 1346, 1715, 2250],
       [ 303,  105,    0,  433,  568,  872, 1172, 1241, 1610, 2145],
       [ 736,  538,  433,    0,  135,  439,  739,  808, 1177, 1712],
       [ 871,  673,  568,  135,    0,  304,  604,  673, 1042, 1577],
       [1175,  977,  872,  439,  304,    0,  300,  369,  738, 1273],
       [1475, 1277, 1172,  739,  604,  300,    0,   69,  438,  973],
       [1544, 1346, 1241,  808,  673,  369,   69,    0,  369,  904],
       [1913, 1715, 1610, 1177, 1042,  738,  438,  369,    0,  535],
       [2448, 2250, 2145, 1712, 1577, 1273,  973,  904,  535,    0]])

In [25]:
M = np.array([[8,5,1,2,],[5,3,8,2]])
M.sort(axis=1)

In [47]:
M = np.array([np.arange(1,6)+5*i for i in np.arange(3)])
M = M.transpose()
print(M)

second_row = M[2,:]
print("Second Row:",second_row)
fourth_row = M[4,:]
print("Fourth Row:",fourth_row)

[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]
('Second Row:', array([ 3,  8, 13]))
('Fourth Row:', array([ 5, 10, 15]))


In [27]:
#
np.arange(1,5)

array([1, 2, 3, 4])

In [48]:
# Alternatively,we can write all the operations in just one line to nake the coder more compact
M = np.array([np.arange(1,6)+5*i for i in np.arange(3)]).transpose()
print(M)
second_row = M[2,:]
print("Second Row:",second_row)
fourth_row = M[4,:]
print("Fourth Row:",fourth_row)

[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]
('Second Row:', array([ 3,  8, 13]))
('Fourth Row:', array([ 5, 10, 15]))


In [58]:
# Another way of implementing this is explained as follows 
# (Using the trabspose function "T" and the reshape function)
M = np.arange(1,16).reshape((3,5)).T
M
# short hand for extracting the elements in the secind and fourth row
M = np.arange(1,16).reshape((3,5)).T[[1,3],:]
M

M[(0,0)] = 1.9
M

# changing the type of the numpy array from integer to float
M.dtype

# 

dtype('int64')