In [21]:
import numpy as np
import matplotlib.pyplot as plt
linalg = np.linalg

N = 1000
mean = [1, 1, 2, 1]
cov = [[1.00, 0.4, 0.35, 0.20],
       [0.40, 1.0, 0, 0],
       [0.35, 0, 1.0, 0],
       [0.20, 0,   0, 1.0]]
data = np.random.multivariate_normal(mean, cov, N)


In [32]:
# Our data is of 4 dimensions and 1000 entries in the obseravtions 
# and is distributed according to the variance-covariance matrix we have defined above
print(data.shape)
print(L.shape)

print

(1000, 4)
(4, 4)


In [37]:
# computing the mean vector
mean_0 = np.mean(data[:,0])
mean_1 = np.mean(data[:,1])
mean_2 = np.mean(data[:,2])
mean_3 = np.mean(data[:,3])
mean_vector = np.array([[mean_0],[mean_1],[mean_2], [mean_3]])
print(mean_vector)

[[ 0.96590233]
 [ 0.99883804]
 [ 2.00969838]
 [ 1.01585087]]


In [43]:
# Var-covar matrix
covariance_matrix = np.cov([data[:,0], data[:,1], data[:,2], data[:,3]])
covariance_matrix.shape
print(covariance_matrix)


[[ 1.04842535  0.39648948  0.39989012  0.2608012 ]
 [ 0.39648948  0.97604434 -0.01451503  0.00415564]
 [ 0.39989012 -0.01451503  1.11649238  0.00784505]
 [ 0.2608012   0.00415564  0.00784505  0.95367707]]


In [63]:
# eigen decomposition of the var-coavar matrix
eigen_val, eigen_vec = linalg.eig(covariance_matrix)
print(eigen_val)
print("Eigen Vectors Follows")
print(eigen_vec)

[ 1.66136439  0.41221491  1.06694272  0.95411711]
Eigen Vectors Follows
[[-0.70910462 -0.69625481  0.11066997  0.0123301 ]
 [-0.40100497  0.49755939  0.61269761 -0.46500678]
 [-0.51361891  0.40196125 -0.74936515 -0.11434438]
 [-0.26937198  0.32571621  0.22540112  0.87780523]]


In [66]:
# sorting the eigen values by decreasing eigen vectors
sorted_index = eigen_val.argsort()
print(sorted_index)

[1 3 2 0]


In [ ]:
sorted_eigenvectors = np.array()

In [ ]:
def Principal_Component_Analysis ()