In [1]:
# Importing the numpy as assigned a short notation for convenience 
import numpy as np
a = np.array([0,1,2,3])
print(a)

[0 1 2 3]


In [3]:
# Measuring the memory and time efficiency
l = range(1000)
%timeit [i**2 for i in l]

The slowest run took 5.39 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 3: 107 µs per loop


In [4]:
% timeit a**2

The slowest run took 26.31 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 725 ns per loop


In [7]:
# seeking for help in numpy
help(np.array)
# naother way
np.array?

np.lookfor("create array")

Help on built-in function array in module numpy.core.multiarray:

array(...)
    array(object, dtype=None, copy=True, order=None, subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an
        object whose __array__ method returns an array, or any
        (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then
        the type will be determined as the minimum type required
        to hold the objects in the sequence.  This argument can only
        be used to 'upcast' the array.  For downcasting, use the
        .astype(t) method.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy
        will only be made if __array__ returns a copy, if obj is a
        nested sequence, or if a copy is needed to satisfy any of the other
        requirements (`dtype`, `order`, etc.).

In [13]:
# checking the dimensions
print(a.ndim)
# shape
print(a.shape)
# length
len(a)

1
(4,)


4

In [14]:
# Mutability of Numpy arrays
print(a)
a[1] = 0
print(a)


[0 1 2 3]
[0 0 2 3]


In [17]:
# copy method for copying the numpy array to another
a = np.array(range(9))
b = a.copy()
print(a)
print(b)

[0 1 2 3 4 5 6 7 8]
[0 1 2 3 4 5 6 7 8]


In [25]:
l = range(9)
l
l[0] = "A"
l[3] = "B"
l[4] = "C"
print(l)

['A', 1, 2, 'B', 'C', 5, 6, 7, 8]


In [26]:
# How will we retrieve A, B, C from the arrays
l[(0,3,4)]

TypeError: list indices must be integers, not tuple

In [31]:
# using the list comprehension, we can access the elements A, B, C
print([l[i] for i in [0,3,4]])
# Also using the map function, we can access the such indices



['A', 'B', 'C']


In [35]:
# Never compare the floating point numbers | Try it in R
l = np.arange(0, 1, 0.1)
l==0.6
# happens becuase of tolerance


array([False, False, False, False, False, False, False, False, False, False], dtype=bool)

In [50]:
# Assignment
l = np.array([[1,1,1,1], [1,1,1,1], [1,1,1,2], [1,6,1,1]])
l

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 2],
       [1, 6, 1, 1]])

In many practical applications, slicing the array happens to be of paramount importance. We now have to think about how to slice the array that we have created. So, it is important to note is how we use **colon operator**, defined by ' : '  for choosing everything and the **range** function for choosing a range of values


In [73]:

np.array(np.diag(np.array([0, 2,3,4,5,6])) ) [:,range(1,6)]

array([[0, 0, 0, 0, 0],
       [2, 0, 0, 0, 0],
       [0, 3, 0, 0, 0],
       [0, 0, 4, 0, 0],
       [0, 0, 0, 5, 0],
       [0, 0, 0, 0, 6]])

In [84]:
# Alternative method
np.delete(np.array(np.diag(np.array(range(1,7)))), 0, axis=1)


array([[0, 0, 0, 0, 0],
       [2, 0, 0, 0, 0],
       [0, 3, 0, 0, 0],
       [0, 0, 4, 0, 0],
       [0, 0, 0, 5, 0],
       [0, 0, 0, 0, 6]])

In [77]:
np.array([ np.tile(np.array([4,3]),3), np.tile(np.array([2,1]),3), 
          np.tile(np.array([4,3]),3), np.tile(np.array([2,1]),3) ])


array([[4, 3, 4, 3, 4, 3],
       [2, 1, 2, 1, 2, 1],
       [4, 3, 4, 3, 4, 3],
       [2, 1, 2, 1, 2, 1]])

In [ ]:
# Type of numpy arrays can be int64 of float64
# we can florce the type at the contruction time
# We also have complex number representations - 64 for real and 64 bits for imaginary parts. total becomes 128
# We can also use strigns which is of type S7


In [98]:
# Copying the A to B and modifying the B thorugh slicing
a = np.array( [np.arange(6)+10*i for i in np.arange(6)] )
print(a)
b = a[4:, 4:]
print(b)
b[0,1] = 10000
print(b)
print(a)
# If you slice a matrix and assign the sliced version to another matrix, 
# the original matrix from which the slice came gets modified

[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]
[[44 45]
 [54 55]]
[[   44 10000]
 [   54    55]]
[[    0     1     2     3     4     5]
 [   10    11    12    13    14    15]
 [   20    21    22    23    24    25]
 [   30    31    32    33    34    35]
 [   40    41    42    43    44 10000]
 [   50    51    52    53    54    55]]


In [ ]:
# To get rid of this situation, use the copy method as following
